//! The record frame, tested through the surface a storage driver sees.
//!
//! Design document §09 fixes the frame and four properties it says may not change. Each of
//! those has a test here that fails if it stops holding:
//!
//! * lengths validated against the caller's buffer *before* anything is read —
//!   [`a_truncated_frame_is_refused_at_every_length`] and
//!   [`arbitrary_bytes_are_never_a_record_and_never_panic`];
//! * unknown record kinds skippable only where the format version permits —
//!   [`an_unknown_kind_is_self_delimiting`] and [`a_scan_will_not_skip_an_unknown_kind`];
//! * padding to the device's program alignment with stale tail bytes never interpreted —
//!   [`padding_is_written_erased_and_never_read_back`] and [`a_scan_walks_padded_frames`];
//! * numeric kinds and borrowed bytes — the decoded record borrows the caller's page,
//!   which [`a_decoded_record_borrows_the_callers_page`] pins.
//!
//! Every one of the six [`RecordRef`] variants has a golden frame: two of them would
//! otherwise be pinned only by the encoder and the decoder agreeing with each other, which
//! is the one comparison a golden vector exists to avoid.
//!
//! # Why the golden frames are not built by the encoder
//!
//! Every byte array in [`golden`] was produced by a reference implementation written
//! separately from this crate, from §09's field list rather than from `frame.rs`. A golden
//! vector generated by the code under test proves only that the code agrees with itself:
//! a wrong magic, a swapped field order or a CRC over the wrong range all round-trip
//! perfectly. These arrays are the one place where the format is stated by something other
//! than the implementation, which is what makes the round-trip tests below mean anything.

use waymaker_core::{ActivityKind, DecodeError, EffectSeq, RecordKind, RecordRef};
use waymaker_flash::frame::{
    self, Decoded, ERASED_BYTE, FORMAT_VERSION, FRAME_OVERHEAD_BYTES, HEADER_BYTES, MAGIC,
    MAX_FRAME_BYTES, MAX_PAYLOAD_BYTES, ProgramAlign, Scan,
};

/// Frames written out by an independent reference implementation of §09's field list.
///
/// The comment above each says what it holds, so a reader can check the bytes by hand
/// against the frame in §09 without running anything.
///
/// `pub` inside a private module is unreachable from anywhere, which is what a fixture is;
/// `pub(super)` would trade this lint for `redundant_pub_crate`, so the allow is here
/// rather than the module reshaped to suit a lint pair that cannot both be satisfied.
#[allow(
    unreachable_pub,
    reason = "a test-only table of golden bytes is reachable from its tests"
)]
mod golden {
    /// `RunStarted { workflow_kind: 0xBEEF, workflow_version: 7, input: b"hi" }`,
    /// alignment 1. Payload is `EF BE 07 00 68 69`.
    pub const RUN_STARTED: [u8; 22] = [
        0x57, 0x4D, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x06, 0x00, 0xB1, 0x4F, 0xEF, 0xBE, 0x07,
        0x00, 0x68, 0x69, 0xE8, 0xD9, 0x09, 0xA3,
    ];

    /// `EffectScheduled { seq: 0x0102_0304, kind: 0x1234, input_len: 0x40,
    /// input_crc: 0xDEAD_BEEF }`, alignment 1. The body is exactly eight bytes.
    pub const EFFECT_SCHEDULED: [u8; 24] = [
        0x57, 0x4D, 0x01, 0x02, 0x04, 0x03, 0x02, 0x01, 0x08, 0x00, 0x17, 0x86, 0x34, 0x12, 0x40,
        0x00, 0xEF, 0xBE, 0xAD, 0xDE, 0x6F, 0xA7, 0xE7, 0x90,
    ];

    /// `EffectCompleted { seq: 9, result: [1, 2, 3] }` at alignment 8: nineteen bytes of
    /// frame followed by five bytes of erased padding.
    pub const EFFECT_COMPLETED_ALIGNED: [u8; 24] = [
        0x57, 0x4D, 0x01, 0x03, 0x09, 0x00, 0x00, 0x00, 0x03, 0x00, 0x45, 0x98, 0x01, 0x02, 0x03,
        0x75, 0x07, 0xBF, 0x96, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    ];

    /// `EffectFailed { seq: 0xFFFF_FFFE, error: [0x00, 0xFF, 0x80] }` at alignment 2:
    /// nineteen bytes of frame and one byte of erased padding. A sequence near the ceiling
    /// and a payload of the two byte values a flash page can hold on its own.
    pub const EFFECT_FAILED: [u8; 20] = [
        0x57, 0x4D, 0x01, 0x04, 0xFE, 0xFF, 0xFF, 0xFF, 0x03, 0x00, 0x93, 0x06, 0x00, 0xFF, 0x80,
        0x9F, 0x7A, 0xD7, 0x43, 0xFF,
    ];

    /// `RunFailed { error: b"why" }`, alignment 1.
    pub const RUN_FAILED: [u8; 19] = [
        0x57, 0x4D, 0x01, 0x08, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x88, 0x9B, 0x77, 0x68, 0x79,
        0x97, 0x11, 0xEE, 0xE0,
    ];

    /// `RunCompleted { result: &[] }`, alignment 1: the shortest frame there is.
    pub const RUN_COMPLETED_EMPTY: [u8; 16] = [
        0x57, 0x4D, 0x01, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x32, 0x44, 0x0B, 0xF6, 0x88,
        0x39,
    ];
}

/// A deterministic generator, so a failure can be reproduced from the seed it names.
///
/// xorshift64, which is not a good random number generator and does not need to be: the
/// tests below want a stream of values that visits payload lengths, record kinds and byte
/// positions a hand-written list would not think of, on a workspace whose layers may not
/// take a dependency of any kind — `proptest` is not available here and would be a
/// dependency-direction violation if it were reached for.
struct Rng(u64);

impl Rng {
    /// Seeded so that zero, the one state xorshift cannot leave, is unreachable.
    const fn new(seed: u64) -> Self {
        Self(seed | 1)
    }

    const fn next_u64(&mut self) -> u64 {
        let mut state = self.0;
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        self.0 = state;
        state
    }

    fn next_u8(&mut self) -> u8 {
        u8::try_from(self.next_u64() & 0xFF).unwrap_or(0)
    }

    /// A value in `0..bound`, or zero when `bound` is zero.
    ///
    /// Modulo bias is irrelevant here and a rejection loop would be a helper that can spin.
    fn below(&mut self, bound: usize) -> usize {
        if bound == 0 {
            return 0;
        }
        let drawn = self.next_u64();
        usize::try_from(drawn % (bound as u64)).unwrap_or(0)
    }
}

/// The six alignments a test sweeps: one that pads nothing, the program sizes real
/// internal flash reports, and a page-sized one.
const ALIGNMENTS: [u16; 6] = [1, 2, 4, 8, 16, 256];

/// Enough room for the longest frame any test below builds.
const SCRATCH: usize = 1024;

/// How many `RecordRef` variants [`sample_record`] can draw.
///
/// Proven equal to the number of variants there are by
/// [`the_sweep_draws_every_record_variant`], which maps each through an exhaustive `match`.
const SAMPLED_VARIANTS: usize = 6;

/// Builds one of the six records from a generator and a borrowed payload.
///
/// Returns the record and nothing else: every assertion belongs in a `#[test]`, because
/// `clippy.toml` exempts test *bodies* from the workspace's `unwrap`, `panic` and
/// `indexing_slicing` denials and does not exempt a helper in an integration test.
fn sample_record<'a>(rng: &mut Rng, payload: &'a [u8]) -> RecordRef<'a> {
    // `SAMPLED_VARIANTS` is the count this dispatch covers, and
    // `the_sweep_draws_every_record_variant` proves by exhaustive `match` that it is every
    // variant there is. A bare `rng.below(6)` beside a hand-written match would silently
    // stop drawing a seventh variant the day one is added — the sweep would keep passing,
    // over five sixths of the enum.
    match rng.below(SAMPLED_VARIANTS) {
        0 => RecordRef::RunStarted {
            workflow_kind: u16::try_from(rng.below(0x1_0000)).unwrap_or(0),
            workflow_version: u16::try_from(rng.below(0x1_0000)).unwrap_or(0),
            input: payload,
        },
        1 => RecordRef::EffectScheduled {
            seq: EffectSeq(u32::try_from(rng.next_u64() >> 32).unwrap_or(0)),
            kind: ActivityKind(u16::try_from(rng.below(0x1_0000)).unwrap_or(0)),
            input_len: u16::try_from(payload.len()).unwrap_or(u16::MAX),
            input_crc: u32::try_from(rng.next_u64() >> 32).unwrap_or(0),
        },
        2 => RecordRef::EffectCompleted {
            seq: EffectSeq(u32::try_from(rng.next_u64() >> 32).unwrap_or(0)),
            result: payload,
        },
        3 => RecordRef::EffectFailed {
            seq: EffectSeq(u32::try_from(rng.next_u64() >> 32).unwrap_or(0)),
            error: payload,
        },
        4 => RecordRef::RunCompleted { result: payload },
        _ => RecordRef::RunFailed { error: payload },
    }
}

/// The record a frame decoded to, or `None` for anything else.
///
/// Total: a malformed frame, an unknown kind and a short buffer all come back as `None`,
/// so a caller in a `#[test]` can assert on the shape rather than on an error type it did
/// not ask about.
fn decoded_record(bytes: &[u8]) -> Option<RecordRef<'_>> {
    match frame::decode(bytes) {
        Ok(frame::Frame {
            decoded: Decoded::Record(record),
            ..
        }) => Some(record),
        _ => None,
    }
}

#[test]
fn the_frame_constants_are_the_ones_section_09_states() {
    // Every one of these is on media for the life of a device, so each is compared with a
    // literal rather than with the constant that defines it.
    assert_eq!(
        MAGIC, 0x4D57,
        "magic reads as b\"WM\" on media, low byte first"
    );
    assert_eq!(FORMAT_VERSION, 1);
    assert_eq!(HEADER_BYTES, 12);
    assert_eq!(FRAME_OVERHEAD_BYTES, 16);
    assert_eq!(MAX_PAYLOAD_BYTES, 65_535);
    assert_eq!(ERASED_BYTE, 0xFF);
    assert_eq!(MAGIC.to_le_bytes(), *b"WM");
}

#[test]
fn the_encoder_writes_the_golden_frames_byte_for_byte() {
    // The one test that can catch a wrong constant, a swapped field or a checksum over the
    // wrong range: the expected bytes came from a reference implementation written from
    // §09 rather than from this crate.
    let cases: [(RecordRef<'_>, u16, &[u8]); 6] = [
        (
            RecordRef::RunStarted {
                workflow_kind: 0xBEEF,
                workflow_version: 7,
                input: b"hi",
            },
            1,
            &golden::RUN_STARTED,
        ),
        (
            RecordRef::EffectScheduled {
                seq: EffectSeq(0x0102_0304),
                kind: ActivityKind(0x1234),
                input_len: 0x40,
                input_crc: 0xDEAD_BEEF,
            },
            1,
            &golden::EFFECT_SCHEDULED,
        ),
        (
            RecordRef::EffectCompleted {
                seq: EffectSeq(9),
                result: &[1, 2, 3],
            },
            8,
            &golden::EFFECT_COMPLETED_ALIGNED,
        ),
        (
            RecordRef::EffectFailed {
                seq: EffectSeq(0xFFFF_FFFE),
                error: &[0x00, 0xFF, 0x80],
            },
            2,
            &golden::EFFECT_FAILED,
        ),
        (
            RecordRef::RunFailed { error: b"why" },
            1,
            &golden::RUN_FAILED,
        ),
        (
            RecordRef::RunCompleted { result: &[] },
            1,
            &golden::RUN_COMPLETED_EMPTY,
        ),
    ];

    for (record, alignment, expected) in cases {
        let align = ProgramAlign::new(alignment).expect("a non-zero alignment");
        let mut page = [0_u8; SCRATCH];
        let written = frame::encode(&record, align, &mut page).expect("room for the frame");

        assert_eq!(written, expected.len(), "{record:?}");
        assert_eq!(&page[..written], expected, "{record:?}");
        assert_eq!(
            frame::encoded_len(&record, align),
            Ok(written),
            "the reserved length and the written length must agree for {record:?}"
        );
    }
}

#[test]
fn the_golden_frames_decode_to_the_records_they_were_built_from() {
    // The other direction, against the same externally produced bytes: an encoder and a
    // decoder that agree with each other but not with §09 pass a round-trip test and fail
    // this one.
    assert_eq!(
        decoded_record(&golden::RUN_STARTED),
        Some(RecordRef::RunStarted {
            workflow_kind: 0xBEEF,
            workflow_version: 7,
            input: b"hi",
        })
    );
    assert_eq!(
        decoded_record(&golden::EFFECT_SCHEDULED),
        Some(RecordRef::EffectScheduled {
            seq: EffectSeq(0x0102_0304),
            kind: ActivityKind(0x1234),
            input_len: 0x40,
            input_crc: 0xDEAD_BEEF,
        })
    );
    assert_eq!(
        decoded_record(&golden::EFFECT_COMPLETED_ALIGNED),
        Some(RecordRef::EffectCompleted {
            seq: EffectSeq(9),
            result: &[1, 2, 3],
        })
    );
    assert_eq!(
        decoded_record(&golden::EFFECT_FAILED),
        Some(RecordRef::EffectFailed {
            seq: EffectSeq(0xFFFF_FFFE),
            error: &[0x00, 0xFF, 0x80],
        })
    );
    assert_eq!(
        decoded_record(&golden::RUN_FAILED),
        Some(RecordRef::RunFailed { error: b"why" })
    );
    assert_eq!(
        decoded_record(&golden::RUN_COMPLETED_EMPTY),
        Some(RecordRef::RunCompleted { result: &[] })
    );
}

#[test]
fn the_sweep_draws_every_record_variant() {
    // The exhaustive `match` is the whole test: a variant added to `RecordRef` is a compile
    // error here, and the only index it can be given is one `sample_record` does not
    // dispatch. Without this, the round-trip sweep below would keep passing while quietly
    // covering a shrinking fraction of the enum.
    const fn index_of(record: &RecordRef<'_>) -> usize {
        match record {
            RecordRef::RunStarted { .. } => 0,
            RecordRef::EffectScheduled { .. } => 1,
            RecordRef::EffectCompleted { .. } => 2,
            RecordRef::EffectFailed { .. } => 3,
            RecordRef::RunCompleted { .. } => 4,
            RecordRef::RunFailed { .. } => 5,
        }
    }

    let mut rng = Rng::new(0x5EED_0006);
    let mut drawn = [false; SAMPLED_VARIANTS];
    for _ in 0..1_000 {
        let record = sample_record(&mut rng, b"payload");
        let index = index_of(&record);
        assert!(
            index < SAMPLED_VARIANTS,
            "{record:?} is outside the dispatch"
        );
        drawn[index] = true;
    }
    assert!(
        drawn.iter().all(|seen| *seen),
        "the generator never drew {:?}",
        drawn
            .iter()
            .enumerate()
            .filter(|(_, seen)| !**seen)
            .map(|(index, _)| index)
            .collect::<Vec<usize>>()
    );
}

#[test]
fn every_record_round_trips_at_every_alignment() {
    // The property the issue asks for, over random records and random payload lengths.
    // Zero and one are drawn explicitly rather than left to chance: they are the lengths
    // an off-by-one lives at, and a uniform draw over a few hundred visits them rarely.
    let mut rng = Rng::new(0x5EED_0001);
    let mut page = [0_u8; SCRATCH];
    let mut payload = [0_u8; 512];
    let mut seen_empty = false;
    let mut seen_long = false;

    for iteration in 0..4_000_u32 {
        let length = match iteration % 8 {
            0 => 0,
            1 => 1,
            2 => payload.len(),
            _ => rng.below(payload.len() + 1),
        };
        for slot in payload.iter_mut().take(length) {
            *slot = rng.next_u8();
        }
        let alignment = ALIGNMENTS[rng.below(ALIGNMENTS.len())];
        let align = ProgramAlign::new(alignment).expect("a non-zero alignment");

        let record = sample_record(&mut rng, &payload[..length]);
        seen_empty |= length == 0;
        seen_long |= length == payload.len();

        let written = frame::encode(&record, align, &mut page)
            .unwrap_or_else(|error| panic!("iteration {iteration}: {error}"));
        assert_eq!(written % usize::from(alignment), 0, "iteration {iteration}");
        assert_eq!(
            frame::encoded_len(&record, align),
            Ok(written),
            "iteration {iteration}"
        );

        let decoded = frame::decode(&page[..written])
            .unwrap_or_else(|error| panic!("iteration {iteration}: {error}"));
        assert_eq!(
            decoded.decoded,
            Decoded::Record(record),
            "iteration {iteration}"
        );
        // The frame's own length excludes the padding, which is what makes the format
        // self-delimiting independently of the device it was written on.
        assert_eq!(
            decoded.frame_len,
            FRAME_OVERHEAD_BYTES + payload_len_of(&record),
            "iteration {iteration}"
        );
        assert!(decoded.frame_len <= written, "iteration {iteration}");
    }

    assert!(
        seen_empty && seen_long,
        "the sweep skipped a boundary length"
    );
}

/// The payload length §09's `payload_len` field holds for `record`.
///
/// Written out here rather than read back from the encoder: a test that asked the code
/// under test how long its own payload is would agree with any answer.
const fn payload_len_of(record: &RecordRef<'_>) -> usize {
    match record {
        RecordRef::RunStarted { input, .. } => 4 + input.len(),
        RecordRef::EffectScheduled { .. } => 8,
        RecordRef::EffectCompleted { result, .. } | RecordRef::RunCompleted { result } => {
            result.len()
        }
        RecordRef::EffectFailed { error, .. } | RecordRef::RunFailed { error } => error.len(),
    }
}

#[test]
fn a_decoded_record_borrows_the_callers_page() {
    // "Borrowed bytes": the decoder hands back a window into the buffer the caller read
    // the page into, not a copy. A decoder that copied would need somewhere to copy to,
    // and this crate has no allocator.
    let mut page = [0_u8; SCRATCH];
    let written = frame::encode(
        &RecordRef::EffectCompleted {
            seq: EffectSeq(4),
            result: b"payload",
        },
        ProgramAlign::BYTE,
        &mut page,
    )
    .expect("room for the frame");

    let Some(RecordRef::EffectCompleted { result, .. }) = decoded_record(&page[..written]) else {
        panic!("the frame holds a completion")
    };
    let offset = HEADER_BYTES;
    assert_eq!(result.as_ptr(), page[offset..].as_ptr());
}

#[test]
fn encode_refuses_an_output_buffer_one_byte_short() {
    // Validated against the caller's buffer before anything is written. One byte short
    // rather than obviously short: a check written as `>` instead of `>=` passes the
    // obvious case.
    let record = RecordRef::RunFailed { error: b"nope" };
    let align = ProgramAlign::new(4).expect("a non-zero alignment");
    let needed = frame::encoded_len(&record, align).expect("an encodable record");

    let mut exact = [0_u8; SCRATCH];
    assert_eq!(
        frame::encode(&record, align, &mut exact[..needed]),
        Ok(needed)
    );

    let mut short = [0_u8; SCRATCH];
    assert_eq!(
        frame::encode(&record, align, &mut short[..needed - 1]),
        Err(DecodeError::LengthOutOfBounds)
    );
    // Nothing was written: a partial frame in a staging buffer is a frame a later flush
    // could program.
    assert!(short.iter().all(|byte| *byte == 0));
}

#[test]
fn encode_refuses_a_payload_the_length_field_cannot_describe() {
    // `payload_len` is a `u16`, so a longer payload has no frame. Refused rather than
    // truncated: a silently shortened record is a record whose bytes are not the ones the
    // workflow returned.
    let oversized = vec![0_u8; MAX_PAYLOAD_BYTES + 1];
    let record = RecordRef::RunCompleted { result: &oversized };
    assert_eq!(
        frame::encoded_len(&record, ProgramAlign::BYTE),
        Err(DecodeError::LengthOutOfBounds)
    );

    // `RunStarted` spends four of those bytes on the workflow identity, so its input
    // ceiling is four lower — the boundary a payload-length check that forgot the header
    // would get wrong.
    let at_limit = vec![0_u8; MAX_PAYLOAD_BYTES - 4];
    assert!(
        frame::encoded_len(
            &RecordRef::RunStarted {
                workflow_kind: 1,
                workflow_version: 1,
                input: &at_limit,
            },
            ProgramAlign::BYTE,
        )
        .is_ok()
    );
    let over_limit = vec![0_u8; MAX_PAYLOAD_BYTES - 3];
    assert_eq!(
        frame::encoded_len(
            &RecordRef::RunStarted {
                workflow_kind: 1,
                workflow_version: 1,
                input: &over_limit,
            },
            ProgramAlign::BYTE,
        ),
        Err(DecodeError::LengthOutOfBounds)
    );
}

#[test]
fn the_longest_frame_round_trips() {
    // The other end of the range from the empty payload: a `payload_len` of `u16::MAX`,
    // where an arithmetic that widened too late would fold back on itself.
    let payload = vec![0xA5_u8; MAX_PAYLOAD_BYTES];
    let record = RecordRef::RunCompleted { result: &payload };
    let align = ProgramAlign::new(256).expect("a non-zero alignment");
    let needed = frame::encoded_len(&record, align).expect("an encodable record");
    let mut page = vec![0_u8; needed];

    assert_eq!(frame::encode(&record, align, &mut page), Ok(needed));
    assert_eq!(decoded_record(&page), Some(record));
}

#[test]
fn a_truncated_frame_is_refused_at_every_length() {
    // "All lengths are validated against caller buffers before reading." Every prefix, not
    // a sample: a bounds check that only covers inputs shorter than the header leaves the
    // payload and the trailer unguarded, and that is exactly the shape of the bug this
    // sweep exists to find.
    for alignment in ALIGNMENTS {
        let align = ProgramAlign::new(alignment).expect("a non-zero alignment");
        let mut page = [0_u8; SCRATCH];
        let written = frame::encode(
            &RecordRef::EffectFailed {
                seq: EffectSeq(2),
                error: b"a longer payload, so the sweep has something to walk through",
            },
            align,
            &mut page,
        )
        .expect("room for the frame");
        let frame_len = FRAME_OVERHEAD_BYTES + 60;

        for length in 0..frame_len {
            assert!(
                frame::decode(&page[..length]).is_err(),
                "alignment {alignment}: a {length}-byte prefix decoded"
            );
        }
        // A frame is complete at `frame_len`, before its padding: the padding belongs to
        // the device rather than to the frame, so a reader must not need it to decode.
        assert!(frame::decode(&page[..frame_len]).is_ok(), "{alignment}");
        assert!(frame::decode(&page[..written]).is_ok(), "{alignment}");
    }
}

#[test]
fn a_single_bit_flip_anywhere_in_a_frame_is_refused() {
    // What the two checksums are for. Swept over every bit of the frame rather than
    // sampled: a checksum computed over the wrong range shows up as some region where a
    // flip changes nothing, and a sample can miss the region.
    //
    // The assertion is `is_none()`, not "not the record we started with". Every byte of a
    // frame is inside `crc16(0..10)`, or is the header checksum, or is inside
    // `crc32(0..12+N)`, or is the frame checksum — so a flip anywhere must be *refused*,
    // and nothing weaker is the property. Asserting only that the result differs from the
    // original would pass for a flip in a payload byte that changed the record into a
    // different, happily-decoded one, which is exactly a decoder with no payload checksum.
    //
    // Swept at every alignment, because the padded frame is a different code path in the
    // encoder and a test that only ever ran at alignment one would never enter it.
    for alignment in ALIGNMENTS {
        let align = ProgramAlign::new(alignment).expect("a non-zero alignment");
        let mut page = [0_u8; SCRATCH];
        let record = RecordRef::EffectCompleted {
            seq: EffectSeq(0x1234_5678),
            result: b"twenty-nine bytes of payload!",
        };
        let written = frame::encode(&record, align, &mut page).expect("room");
        let frame_len = FRAME_OVERHEAD_BYTES + 29;

        for index in 0..frame_len {
            for bit in 0..8 {
                let mut damaged = page;
                damaged[index] ^= 1 << bit;
                assert!(
                    decoded_record(&damaged[..written]).is_none(),
                    "alignment {alignment}, byte {index} bit {bit} still decoded"
                );
            }
        }

        // The pad is the complement of that claim: a flip there changes nothing, because
        // nothing reads it.
        for index in frame_len..written {
            for bit in 0..8 {
                let mut stale = page;
                stale[index] ^= 1 << bit;
                assert_eq!(
                    decoded_record(&stale[..written]),
                    Some(record),
                    "alignment {alignment}, pad byte {index} bit {bit} was interpreted"
                );
            }
        }
    }
}

#[test]
fn arbitrary_bytes_are_never_a_record_and_never_panic() {
    // The bounded-decoding guarantee, from the outside. `#![forbid(unsafe_code)]` and the
    // workspace's denial of `indexing_slicing` mean an out-of-bounds *read* is not
    // expressible here; what is expressible is a panic, and on this target
    // `panic = "abort"` makes a panic a bricked device. So the property under test is that
    // the decoder returns.
    let mut rng = Rng::new(0x5EED_0002);
    let mut buffer = [0_u8; 128];

    for _ in 0..20_000 {
        let length = rng.below(buffer.len() + 1);
        for slot in buffer.iter_mut().take(length) {
            *slot = rng.next_u8();
        }
        // Random bytes almost never carry the magic, so this sweep on its own would test
        // the first check and nothing else. `mutating_a_valid_frame_reaches_every_refusal`
        // is what walks the deep paths; this one is here for the shallow ones and for
        // lengths a valid frame never has.
        assert!(decoded_record(&buffer[..length]).is_none());
    }
}

#[test]
fn damaging_a_frame_without_resealing_it_is_always_caught() {
    // The honest half of the fuzz for the checksums. Starting from a frame that decodes
    // and damaging a few bytes puts the generator *inside* the decoder rather than at its
    // front door — random buffers hardly ever carry the magic, so a blind sweep tests the
    // first check and nothing else.
    //
    // Nothing here reseals, so every edit is a corruption the two checksums exist to
    // catch, and the property is that not one of thirty thousand gets through.
    let mut rng = Rng::new(0x5EED_0003);
    let mut page = [0_u8; SCRATCH];
    let clean = frame::encode(
        &RecordRef::EffectScheduled {
            seq: EffectSeq(7),
            kind: ActivityKind(3),
            input_len: 16,
            input_crc: 0x0BAD_F00D,
        },
        ProgramAlign::BYTE,
        &mut page,
    )
    .expect("room for the frame");

    let mut integrity = 0_u32;
    let mut truncated = 0_u32;

    for _ in 0..30_000 {
        let mut damaged = page;
        let edits = 1 + rng.below(3);
        for _ in 0..edits {
            let at = rng.below(clean);
            damaged[at] ^= 1 << rng.below(8);
        }
        // A flip is its own inverse, so two edits at the same bit leave the frame
        // pristine — and a pristine frame decoding is not a finding. Discarded here rather
        // than avoided in the generator, because the generator that avoided it would be
        // the thing under test.
        if damaged[..clean] == page[..clean] {
            continue;
        }
        let length = if rng.below(4) == 0 {
            rng.below(clean + 1)
        } else {
            clean
        };

        match frame::decode(&damaged[..length]) {
            // A damaged frame that still decodes is a checksum collision. Against a
            // 32-bit checksum over thirty thousand draws, the expected count is a small
            // fraction of one.
            Ok(frame) => panic!("a damaged frame decoded as {frame:?}"),
            Err(DecodeError::IntegrityFailed) => integrity += 1,
            Err(DecodeError::Truncated) => truncated += 1,
            Err(other) => panic!("an unresealed frame reached {other}"),
        }
    }

    assert!(integrity > 0, "no frame failed a checksum");
    assert!(truncated > 0, "no frame was cut short");
}

#[test]
fn resealing_a_damaged_frame_reaches_every_check_past_the_checksums() {
    // The other half, and the one that matters for coverage. A checksum is doing its job
    // when it rejects a random edit — which is exactly why a sweep that does not reseal
    // can never reach the version check, the kind check or the body checks: those are all
    // behind two checksums that a random edit will not satisfy.
    //
    // So this sweep damages a byte and then recomputes both checksums, the way a wrong
    // encoder or a hostile writer would. What it produces is a frame that is *internally
    // consistent* and still not a record this firmware may accept, and the counters at the
    // end are what prove the generator got that far rather than being turned away at the
    // door.
    let mut rng = Rng::new(0x5EED_0005);
    let mut page = [0_u8; SCRATCH];
    let clean = frame::encode(
        &RecordRef::EffectScheduled {
            seq: EffectSeq(7),
            kind: ActivityKind(3),
            input_len: 16,
            input_crc: 0x0BAD_F00D,
        },
        ProgramAlign::BYTE,
        &mut page,
    )
    .expect("room for the frame");

    let mut integrity = 0_u32;
    let mut unsupported_version = 0_u32;
    let mut unknown_kind = 0_u32;
    let mut malformed = 0_u32;
    let mut truncated = 0_u32;
    let mut accepted = 0_u32;

    for _ in 0..30_000 {
        let mut damaged = page;
        let edits = 1 + rng.below(3);
        for _ in 0..edits {
            let at = rng.below(clean);
            damaged[at] = rng.next_u8();
        }
        reseal(&mut damaged[..clean]);
        let length = if rng.below(4) == 0 {
            rng.below(clean + 1)
        } else {
            clean
        };

        match frame::decode(&damaged[..length]) {
            Ok(frame::Frame {
                decoded: Decoded::Record(_),
                ..
            }) => accepted += 1,
            Ok(frame::Frame {
                decoded: Decoded::UnknownKind(_),
                ..
            }) => unknown_kind += 1,
            Err(DecodeError::IntegrityFailed) => integrity += 1,
            Err(DecodeError::UnsupportedFormatVersion) => unsupported_version += 1,
            Err(DecodeError::MalformedRecord) => malformed += 1,
            Err(DecodeError::Truncated) => truncated += 1,
            Err(DecodeError::LengthOutOfBounds | DecodeError::UnknownRecordKind) => {
                panic!("decode returned an error it documents that it never returns")
            }
        }
    }

    // Every one of these is a distinct decision the decoder takes after both checksums
    // have held. A zero would mean the sweep never exercised it, which is what makes an
    // impressive-looking fuzz test decorative.
    assert!(
        integrity > 0,
        "the magic was never damaged; resealing does not repair it"
    );
    assert!(truncated > 0, "no resealed frame was cut short");
    assert!(
        unsupported_version > 0,
        "the version byte was never damaged into an unsupported one"
    );
    assert!(unknown_kind > 0, "the kind byte was never damaged");
    assert!(
        malformed > 0,
        "no frame reached the body checks with a body that did not fit its kind"
    );
    assert!(
        accepted > 0,
        "no resealed frame decoded, so the sweep never got past the checksums at all"
    );
}

#[test]
fn an_unsupported_format_version_is_refused() {
    // The version is checked after the header checksum and before anything the version
    // could have changed the meaning of. A firmware that cannot read a journal has to say
    // so rather than read it under this version's rules.
    let mut page = [0_u8; SCRATCH];
    let written = frame::encode(
        &RecordRef::RunFailed { error: b"x" },
        ProgramAlign::BYTE,
        &mut page,
    )
    .expect("room");

    let mut future = page;
    future[2] = FORMAT_VERSION + 1;
    reseal(&mut future[..written]);
    assert_eq!(
        frame::decode(&future[..written]),
        Err(DecodeError::UnsupportedFormatVersion)
    );
}

/// Recomputes both checksums over a frame whose fields a test has edited.
///
/// Without this, every edit below would be rejected as a checksum failure before it
/// reached the check it was written to exercise — which would make each of those tests
/// pass for the wrong reason.
fn reseal(frame_bytes: &mut [u8]) {
    let header_crc = crc16(frame_bytes.get(..HEADER_BYTES - 2).unwrap_or_default());
    for (slot, byte) in frame_bytes
        .iter_mut()
        .skip(HEADER_BYTES - 2)
        .zip(header_crc.to_le_bytes())
    {
        *slot = byte;
    }

    // The covered range comes from the `payload_len` in the header, never from the length
    // of the slice handed in. Deriving it from the slice would be right only when there is
    // no padding, so the first tamper test written at an alignment above one would reseal
    // over the pad and pass for the wrong reason — and it would look like it was testing
    // the padded path.
    let payload_len = frame_bytes
        .get(HEADER_BYTES - 4..HEADER_BYTES - 2)
        .and_then(|slice| <[u8; 2]>::try_from(slice).ok())
        .map_or(0, |bytes| usize::from(u16::from_le_bytes(bytes)));
    let covered = HEADER_BYTES.saturating_add(payload_len);
    let frame_crc = crc32(frame_bytes.get(..covered).unwrap_or_default());
    for (slot, byte) in frame_bytes
        .iter_mut()
        .skip(covered)
        .zip(frame_crc.to_le_bytes())
    {
        *slot = byte;
    }
}

/// CRC-16/CCITT-FALSE, written out again here on purpose.
///
/// The crate's own implementation is private, and a test that reached for it would be
/// resealing an edited frame with the very code the frame's checksums are supposed to be
/// an independent check on. Anchored to the catalogue by
/// [`the_tests_own_checksums_reproduce_the_published_check_values`]: a second copy of one
/// wrong polynomial agrees with the first perfectly, and every golden vector, round trip
/// and tamper test built on the pair would be consistent with nothing outside this
/// repository.
fn crc16(bytes: &[u8]) -> u16 {
    let mut crc: u16 = 0xFFFF;
    for byte in bytes {
        crc ^= u16::from(*byte) << 8;
        for _ in 0..8 {
            crc = if crc & 0x8000 == 0 {
                crc << 1
            } else {
                (crc << 1) ^ 0x1021
            };
        }
    }
    crc
}

/// CRC-32/ISO-HDLC, written out again here for the same reason as [`crc16`].
fn crc32(bytes: &[u8]) -> u32 {
    let mut crc: u32 = 0xFFFF_FFFF;
    for byte in bytes {
        crc ^= u32::from(*byte);
        for _ in 0..8 {
            crc = if crc & 1 == 0 {
                crc >> 1
            } else {
                (crc >> 1) ^ 0xEDB8_8320
            };
        }
    }
    crc ^ 0xFFFF_FFFF
}

#[test]
fn the_tests_own_checksums_reproduce_the_published_check_values() {
    // This file carries its own `crc16` and `crc32` so that `reseal` does not edit a frame
    // with the code under test. A second implementation needs an anchor of its own, or it
    // is just a second chance to make the same mistake — these are the values every
    // specification of these two algorithms states for `b"123456789"`.
    assert_eq!(crc16(b"123456789"), 0x29B1, "CRC-16/CCITT-FALSE");
    assert_eq!(crc32(b"123456789"), 0xCBF4_3926, "CRC-32/ISO-HDLC");
}

#[test]
fn every_decodable_record_kind_decodes_to_a_record() {
    // `decode_body`'s last arm is a wildcard that turns any unrecognised kind into
    // `Decoded::UnknownKind`. That is right for a kind this firmware does not know and
    // wrong for one it forgot: a decode arm left out when a variant is added produces a
    // green build with a record type that can be written and never read. Coverage cannot
    // see it — the wildcard is exercised either way — so the completeness is asserted here.
    let cases: [(RecordKind, RecordRef<'_>); 6] = [
        (
            RecordKind::RUN_STARTED,
            RecordRef::RunStarted {
                workflow_kind: 9,
                workflow_version: 2,
                input: b"in",
            },
        ),
        (
            RecordKind::EFFECT_SCHEDULED,
            RecordRef::EffectScheduled {
                seq: EffectSeq(1),
                kind: ActivityKind(2),
                input_len: 3,
                input_crc: 4,
            },
        ),
        (
            RecordKind::EFFECT_COMPLETED,
            RecordRef::EffectCompleted {
                seq: EffectSeq(1),
                result: b"ok",
            },
        ),
        (
            RecordKind::EFFECT_FAILED,
            RecordRef::EffectFailed {
                seq: EffectSeq(1),
                error: b"no",
            },
        ),
        (
            RecordKind::RUN_COMPLETED,
            RecordRef::RunCompleted { result: b"r" },
        ),
        (RecordKind::RUN_FAILED, RecordRef::RunFailed { error: b"e" }),
    ];

    for (kind, record) in cases {
        assert_eq!(record.kind(), kind, "{record:?} wears the wrong number");
        let mut page = [0_u8; SCRATCH];
        let written = frame::encode(&record, ProgramAlign::BYTE, &mut page).expect("room");
        assert_eq!(
            frame::decode(&page[..written]).map(|frame| frame.decoded),
            Ok(Decoded::Record(record)),
            "{kind:?} encodes but does not decode back to a record"
        );
    }

    // The reserved kinds are the complement: known numbers this firmware deliberately
    // cannot read, so a decoder that grew an arm for one of them by accident shows up here.
    for reserved in [
        RecordKind::TIMER_SCHEDULED,
        RecordKind::TIMER_FIRED,
        RecordKind::VERSION_MARKER,
        RecordKind::SIGNAL_RECEIVED,
        RecordKind::CHILD_STARTED,
    ] {
        let mut page = [0_u8; SCRATCH];
        let written = frame::encode(
            &RecordRef::RunCompleted { result: b"body" },
            ProgramAlign::BYTE,
            &mut page,
        )
        .expect("room");
        page[3] = reserved.0;
        reseal(&mut page[..written]);
        assert_eq!(
            frame::decode(&page[..written]).map(|frame| frame.decoded),
            Ok(Decoded::UnknownKind(reserved)),
            "{reserved:?} is reserved for a later issue and must not decode yet"
        );
    }
}

#[test]
fn a_run_scoped_record_may_not_carry_an_effect_sequence() {
    // `RunStarted`, `RunCompleted` and `RunFailed` belong to the run rather than to an
    // effect, so the encoder writes zero into `effect_seq` and the decoder insists on it.
    // The alternative — ignoring the field for those kinds — would let two different byte
    // sequences decode to one record, and a format meant to be frozen is easier to reason
    // about when the decoder rejects everything the encoder cannot produce.
    let mut page = [0_u8; SCRATCH];
    for record in [
        RecordRef::RunStarted {
            workflow_kind: 1,
            workflow_version: 1,
            input: b"i",
        },
        RecordRef::RunCompleted { result: b"r" },
        RecordRef::RunFailed { error: b"e" },
    ] {
        let written = frame::encode(&record, ProgramAlign::BYTE, &mut page).expect("room");
        assert_eq!(page[4..8], [0, 0, 0, 0], "{record:?} wrote a sequence");

        let mut tampered = page;
        tampered[4] = 1;
        reseal(&mut tampered[..written]);
        assert_eq!(
            frame::decode(&tampered[..written]),
            Err(DecodeError::MalformedRecord),
            "{record:?}"
        );
    }
}

#[test]
fn a_body_that_does_not_fit_its_kind_is_refused() {
    // A frame can be structurally perfect — magic, checksums, a known kind — and still not
    // be the record it claims. `EffectScheduled` is exactly eight bytes of body and
    // `RunStarted` is at least four; anything else is a decoder reading fields that are
    // not there.
    // Every rejection is paired with its nearest *accepted* neighbour, reached through the
    // identical tamper path. Without the accepted rows, a decoder that refused every
    // kind-substituted frame — or refused every frame at all — would pass this test, and the
    // table would look like it was checking body shapes when it was checking nothing.
    for (kind, payload, expected) in [
        (
            RecordKind::EFFECT_SCHEDULED,
            7_usize,
            Err(DecodeError::MalformedRecord),
        ),
        (RecordKind::EFFECT_SCHEDULED, 8, Ok(())),
        (
            RecordKind::EFFECT_SCHEDULED,
            9,
            Err(DecodeError::MalformedRecord),
        ),
        (
            RecordKind::RUN_STARTED,
            3,
            Err(DecodeError::MalformedRecord),
        ),
        (RecordKind::RUN_STARTED, 4, Ok(())),
        (RecordKind::RUN_STARTED, 5, Ok(())),
        // A body of any length fits a completion, which is what makes the two rejections
        // above real constraints rather than a decoder that refuses short payloads
        // everywhere.
        (RecordKind::EFFECT_COMPLETED, 0, Ok(())),
        (RecordKind::EFFECT_COMPLETED, 3, Ok(())),
    ] {
        let mut page = [0_u8; SCRATCH];
        let filler = vec![0_u8; payload];
        let written = frame::encode(
            &RecordRef::RunCompleted { result: &filler },
            ProgramAlign::BYTE,
            &mut page,
        )
        .expect("room");

        page[3] = kind.0;
        reseal(&mut page[..written]);
        assert_eq!(
            frame::decode(&page[..written]).map(|_| ()),
            expected,
            "kind {kind:?} with a {payload}-byte body"
        );
    }
}

#[test]
fn an_unknown_kind_is_self_delimiting() {
    // The property that makes forward compatibility possible at all: a reader that cannot
    // interpret a record can still say where it ends, because the length is in the header
    // and the header is checksummed on its own. `TimerScheduled` is the real case — a
    // v0.1-required record whose body arrives with the timer issue — so the number is
    // reserved and this is what a firmware built before that issue sees.
    let mut page = [0_u8; SCRATCH];
    let written = frame::encode(
        &RecordRef::RunCompleted { result: b"body" },
        ProgramAlign::BYTE,
        &mut page,
    )
    .expect("room");

    page[3] = RecordKind::TIMER_SCHEDULED.0;
    reseal(&mut page[..written]);

    assert_eq!(
        frame::decode(&page[..written]),
        Ok(frame::Frame {
            format_version: FORMAT_VERSION,
            decoded: Decoded::UnknownKind(RecordKind::TIMER_SCHEDULED),
            frame_len: written,
        })
    );
}

#[test]
fn padding_is_written_erased_and_never_read_back() {
    // "Records padded to the device's program alignment, with stale tail bytes never
    // interpreted." Padding is written as `0xFF` because that is what an erased NOR cell
    // already holds, so programming it changes no bits; and the decoder's reported length
    // stops at the frame, so a reader never treats the pad as data.
    let record = RecordRef::EffectCompleted {
        seq: EffectSeq(1),
        result: b"five!",
    };
    let align = ProgramAlign::new(16).expect("a non-zero alignment");
    let mut page = [0_u8; SCRATCH];
    let written = frame::encode(&record, align, &mut page).expect("room");

    let frame_len = FRAME_OVERHEAD_BYTES + 5;
    assert_eq!(written, 32, "21 bytes of frame padded up to 16-byte units");
    assert!(
        page[frame_len..written]
            .iter()
            .all(|byte| *byte == ERASED_BYTE)
    );

    let decoded = frame::decode(&page[..written]).expect("a valid frame");
    assert_eq!(decoded.frame_len, frame_len);
    assert_eq!(decoded.decoded, Decoded::Record(record));

    // Stale bytes where the pad is: still the same record, because nothing reads them.
    let mut stale = page;
    for slot in stale.iter_mut().take(written).skip(frame_len) {
        *slot = 0x5A;
    }
    assert_eq!(decoded_record(&stale[..written]), Some(record));
}

#[test]
fn an_alignment_must_be_non_zero() {
    // Zero is not "no padding", it is a division by zero. Rejected once at construction
    // rather than guarded at every use.
    assert!(ProgramAlign::new(0).is_none());
    assert_eq!(ProgramAlign::new(1).map(ProgramAlign::get), Some(1));
    assert_eq!(ProgramAlign::BYTE.get(), 1);
    assert_eq!(ProgramAlign::new(256).map(ProgramAlign::get), Some(256));

    let align = ProgramAlign::new(8).expect("a non-zero alignment");
    assert_eq!(align.round_up(0), Some(0));
    assert_eq!(align.round_up(1), Some(8));
    assert_eq!(align.round_up(8), Some(8));
    assert_eq!(align.round_up(9), Some(16));
    // A length that cannot be rounded up without wrapping has no answer, rather than an
    // answer that is smaller than the input.
    assert_eq!(align.round_up(usize::MAX), None);
    assert_eq!(ProgramAlign::BYTE.round_up(usize::MAX), Some(usize::MAX));
    // An alignment real flash never reports is still arithmetic that has to be right.
    let odd = ProgramAlign::new(3).expect("a non-zero alignment");
    assert_eq!(odd.round_up(4), Some(6));
}

#[test]
fn a_scan_walks_padded_frames_and_stops_at_the_erased_tail() {
    // What recovery does: walk the journal in order until the bytes stop being records.
    // An erased tail is the ordinary end of history rather than damage, so it ends the
    // scan without an error.
    let align = ProgramAlign::new(16).expect("a non-zero alignment");
    let records = [
        RecordRef::RunStarted {
            workflow_kind: 4,
            workflow_version: 1,
            input: b"start",
        },
        RecordRef::EffectScheduled {
            seq: EffectSeq(0),
            kind: ActivityKind(1),
            input_len: 3,
            input_crc: 0x1234_5678,
        },
        RecordRef::EffectCompleted {
            seq: EffectSeq(0),
            result: b"done",
        },
        RecordRef::RunCompleted { result: &[] },
    ];

    let mut journal = [ERASED_BYTE; SCRATCH];
    let mut at = 0;
    for record in records {
        let written =
            frame::encode(&record, align, &mut journal[at..]).expect("room in the journal");
        at += written;
    }

    let mut scan = Scan::new(&journal, align);
    let walked: Vec<Result<RecordRef<'_>, DecodeError>> = scan.by_ref().collect();
    assert_eq!(walked, records.map(Ok).to_vec());
    assert_eq!(
        scan.offset(),
        at,
        "the scan stops where the next append goes"
    );
    // Fused: a scan that ended is a scan that stays ended, so a caller that keeps asking
    // does not restart the journal.
    assert!(scan.next().is_none());
    assert!(scan.next().is_none());
}

#[test]
fn a_scan_stops_at_the_first_damaged_frame_and_reports_where() {
    // §09: "Recovery stops at the first unsealed, malformed, out-of-sequence, or
    // integrity-failed frame." The prefix before the damage is history; nothing after it
    // is, even if it happens to decode.
    let align = ProgramAlign::BYTE;
    let mut journal = [ERASED_BYTE; SCRATCH];

    let first = frame::encode(
        &RecordRef::RunStarted {
            workflow_kind: 1,
            workflow_version: 1,
            input: b"a",
        },
        align,
        &mut journal,
    )
    .expect("room");
    let second = frame::encode(
        &RecordRef::EffectCompleted {
            seq: EffectSeq(0),
            result: b"b",
        },
        align,
        &mut journal[first..],
    )
    .expect("room");
    let third_at = first + second;
    frame::encode(
        &RecordRef::RunCompleted { result: b"c" },
        align,
        &mut journal[third_at..],
    )
    .expect("room");

    // A bit flip in the middle frame's payload.
    journal[first + HEADER_BYTES] ^= 0x01;

    let mut scan = Scan::new(&journal, align);
    assert_eq!(
        scan.next(),
        Some(Ok(RecordRef::RunStarted {
            workflow_kind: 1,
            workflow_version: 1,
            input: b"a",
        }))
    );
    assert_eq!(scan.next(), Some(Err(DecodeError::IntegrityFailed)));
    // The third frame is intact and is still not history: everything after the first
    // failure is outside the committed prefix.
    assert!(scan.next().is_none());
    assert_eq!(
        scan.offset(),
        first,
        "the append point is the start of the frame that failed"
    );
}

#[test]
fn a_scan_will_not_skip_an_unknown_kind() {
    // "Unknown record kinds are skippable only when the format version permits forward
    // compatibility." Format version 1 does not permit it, so a reader that meets a record
    // it cannot interpret stops rather than guessing that the rest of history is
    // unaffected by it — a skipped `TimerFired` is a timer replay believes never happened.
    let align = ProgramAlign::BYTE;
    let mut journal = [ERASED_BYTE; SCRATCH];
    let first = frame::encode(
        &RecordRef::RunStarted {
            workflow_kind: 1,
            workflow_version: 1,
            input: b"a",
        },
        align,
        &mut journal,
    )
    .expect("room");
    let second = frame::encode(
        &RecordRef::RunCompleted { result: b"later" },
        align,
        &mut journal[first..],
    )
    .expect("room");

    journal[first + 3] = RecordKind::TIMER_FIRED.0;
    reseal(&mut journal[first..first + second]);

    let mut scan = Scan::new(&journal, align);
    assert!(matches!(
        scan.next(),
        Some(Ok(RecordRef::RunStarted { .. }))
    ));
    assert_eq!(scan.next(), Some(Err(DecodeError::UnknownRecordKind)));
    assert!(scan.next().is_none());
    assert_eq!(scan.offset(), first);
}

#[test]
fn a_scan_of_an_empty_or_erased_journal_yields_nothing() {
    // Both are the state a device is in before it has written anything, and neither is an
    // error. A scanner that reported damage here would make every first boot look like a
    // corrupted one.
    let erased = [ERASED_BYTE; 64];
    let mut scan = Scan::new(&erased, ProgramAlign::BYTE);
    assert!(scan.next().is_none());
    assert_eq!(scan.offset(), 0);

    let mut empty = Scan::new(&[], ProgramAlign::BYTE);
    assert!(empty.next().is_none());
    assert_eq!(empty.offset(), 0);

    // Fewer bytes than a header: nothing that could be a frame, so the same answer.
    let stub = [ERASED_BYTE; HEADER_BYTES - 1];
    let mut short = Scan::new(&stub, ProgramAlign::BYTE);
    assert!(short.next().is_none());
}

#[test]
fn a_scan_always_terminates_and_advances() {
    // The scanner is the one loop in this crate, so it is the one place a malformed journal
    // could hang rather than fail.
    //
    // Random bytes alone cannot test that: they never carry the magic, so the scan stops on
    // its first step every time and a step counter never exceeds one. Half the journals here
    // are therefore built from real frames and then damaged, which is what produces scans of
    // several steps — and the test asserts it saw them, so a generator that stopped
    // producing them is a failure rather than a quiet return to testing nothing.
    let mut rng = Rng::new(0x5EED_0004);
    let mut journal = [0_u8; 512];
    let mut deepest = 0;

    for iteration in 0..2_000 {
        let align = ProgramAlign::new(ALIGNMENTS[rng.below(ALIGNMENTS.len())])
            .expect("a non-zero alignment");

        if iteration % 2 == 0 {
            for slot in &mut journal {
                *slot = rng.next_u8();
            }
        } else {
            // A run of real frames, then a few random bytes somewhere in it.
            journal.fill(ERASED_BYTE);
            let mut at = 0;
            for index in 0..6_u32 {
                let record = RecordRef::EffectCompleted {
                    seq: EffectSeq(index),
                    result: b"payload",
                };
                match frame::encode(&record, align, &mut journal[at..]) {
                    Ok(written) => at += written,
                    Err(_) => break,
                }
            }
            for _ in 0..rng.below(4) {
                let at = rng.below(journal.len());
                journal[at] = rng.next_u8();
            }
        }

        let mut scan = Scan::new(&journal, align);
        let mut steps = 0;
        while scan.next().is_some() {
            steps += 1;
            assert!(
                steps <= journal.len() / FRAME_OVERHEAD_BYTES + 1,
                "iteration {iteration}: the scan did not advance"
            );
        }
        deepest = deepest.max(steps);
        assert!(scan.offset() <= journal.len(), "iteration {iteration}");
    }

    assert!(
        deepest > 1,
        "no journal took more than one step, so nothing here tested advancing"
    );
}

#[test]
fn a_scan_offset_never_passes_the_end_of_its_journal() {
    // `Scan::offset` promises "never greater than the journal's length", and the clamp that
    // keeps that promise is reachable: a journal sliced to exactly one frame, whose padding
    // the writer put beyond the slice, has a stride longer than the bytes on offer.
    let align = ProgramAlign::new(16).expect("a non-zero alignment");
    let mut page = [0_u8; SCRATCH];
    let record = RecordRef::RunCompleted { result: b"abc" };
    let written = frame::encode(&record, align, &mut page).expect("room");
    let frame_len = FRAME_OVERHEAD_BYTES + 3;
    assert!(
        written > frame_len,
        "the record must be padded for this to test anything"
    );

    // Hand the scan the frame and none of its padding.
    let mut scan = Scan::new(&page[..frame_len], align);
    assert_eq!(scan.next(), Some(Ok(record)));
    assert_eq!(
        scan.offset(),
        frame_len,
        "the offset is clamped to the journal rather than to the padded stride"
    );
    assert!(scan.next().is_none());
}

#[test]
fn a_scan_reads_its_slice_as_the_whole_journal() {
    // `Scan`'s erased-tail rule is "an erased header *and* erased to the end", which is what
    // catches a stride mismatch — and which makes the slice a precondition rather than
    // merely a bound: bytes after the last frame that are not erased are damage as far as
    // this type is concerned. A caller with a bank header or a generation seal in the same
    // erase block passes the journal region, not the block.
    //
    // Pinned here because it is the shape rung 0.2 arrives in, and a caller that gets it
    // wrong sees a perfectly good journal reported as corrupt on every boot.
    let align = ProgramAlign::new(8).expect("a non-zero alignment");
    let mut block = [ERASED_BYTE; 256];
    let written =
        frame::encode(&RecordRef::RunCompleted { result: b"r" }, align, &mut block).expect("room");

    // Something that is not a record living at the end of the same erase block.
    block[252..256].copy_from_slice(&[0xDE, 0xAD, 0xBE, 0xEF]);

    let mut whole_block = Scan::new(&block, align);
    assert!(matches!(
        whole_block.next(),
        Some(Ok(RecordRef::RunCompleted { .. }))
    ));
    assert_eq!(
        whole_block.next(),
        Some(Err(DecodeError::IntegrityFailed)),
        "a non-erased tail is damage, which is the price of catching a stride mismatch"
    );

    // The journal region alone reads clean, which is the contract.
    let mut journal_only = Scan::new(&block[..252], align);
    assert!(matches!(
        journal_only.next(),
        Some(Ok(RecordRef::RunCompleted { .. }))
    ));
    assert!(journal_only.next().is_none());
    assert_eq!(journal_only.offset(), written);
}

#[test]
fn a_scan_at_a_larger_alignment_than_the_writer_used_is_not_caught() {
    // The other half of the stride mismatch, pinned because it is *not* handled. A reader
    // striding by more than the writer used steps over whole frames and lands on erased
    // bytes, which is an ordinary end of history in every respect the scan can see. There is
    // nothing on media to check it against.
    //
    // So this test asserts the wrong answer on purpose. It is the record that the limitation
    // is known and bounded rather than undiscovered, and it fails the day rung 0.2 puts the
    // writer's program size in the bank header and makes the right answer possible.
    let writer = ProgramAlign::new(8).expect("a non-zero alignment");
    let mut journal = [ERASED_BYTE; 2_048];
    let mut at = 0;
    for index in 0..4_u32 {
        let record = RecordRef::EffectCompleted {
            seq: EffectSeq(index),
            result: b"x",
        };
        at += frame::encode(&record, writer, &mut journal[at..]).expect("room");
    }

    let mut over_striding = Scan::new(&journal, ProgramAlign::new(256).expect("non-zero"));
    assert!(matches!(
        over_striding.next(),
        Some(Ok(RecordRef::EffectCompleted { .. }))
    ));
    assert!(
        over_striding.next().is_none(),
        "known limitation: a larger stride steps over the remaining frames"
    );
    assert_ne!(
        over_striding.offset(),
        at,
        "and reports an offset that is not where history ended"
    );
}

#[test]
fn a_scan_survives_a_journal_that_ends_mid_frame() {
    // The torn-write case from §14: a frame whose header is durable and whose payload is
    // not. It cannot be history, and the scan has to say so rather than read past the end
    // of the bank.
    let mut page = [0_u8; SCRATCH];
    let written = frame::encode(
        &RecordRef::RunCompleted {
            result: b"a payload that will not all be there",
        },
        ProgramAlign::BYTE,
        &mut page,
    )
    .expect("room");

    for cut in HEADER_BYTES..written {
        let mut scan = Scan::new(&page[..cut], ProgramAlign::BYTE);
        assert_eq!(
            scan.next(),
            Some(Err(DecodeError::Truncated)),
            "a frame cut to {cut} bytes"
        );
        assert!(scan.next().is_none());
        assert_eq!(scan.offset(), 0);
    }
}

#[test]
fn the_golden_frames_hold_the_fields_section_09_puts_at_those_offsets() {
    // The golden arrays are opaque blobs everywhere else in this file, and a blob compared
    // with a blob cannot show a reader — or a reviewer — that the bytes are the right ones.
    // Here each is taken apart at literal offsets against §09's field list, so a paste error
    // or a vector regenerated from a broken encoder is visible without running anything.
    let g = golden::RUN_STARTED;
    assert_eq!(&g[0..2], b"WM", "magic, low byte first");
    assert_eq!(g[2], 1, "format_version");
    assert_eq!(g[3], 1, "record_kind: RunStarted");
    assert_eq!(
        u32::from_le_bytes([g[4], g[5], g[6], g[7]]),
        0,
        "effect_seq"
    );
    assert_eq!(
        u16::from_le_bytes([g[8], g[9]]),
        6,
        "payload_len: four bytes of workflow identity plus two of input"
    );
    assert_eq!(
        u16::from_le_bytes([g[10], g[11]]),
        crc16(&g[0..10]),
        "header_crc covers exactly the ten bytes before it, payload_len included"
    );
    assert_eq!(u16::from_le_bytes([g[12], g[13]]), 0xBEEF, "workflow_kind");
    assert_eq!(u16::from_le_bytes([g[14], g[15]]), 7, "workflow_version");
    assert_eq!(&g[16..18], b"hi", "input");
    assert_eq!(
        u32::from_le_bytes([g[18], g[19], g[20], g[21]]),
        crc32(&g[0..18]),
        "payload_crc covers the header as well as the payload"
    );
    assert_eq!(
        g.len(),
        22,
        "sixteen bytes of overhead plus a six-byte payload"
    );

    let s = golden::EFFECT_SCHEDULED;
    assert_eq!(&s[0..2], b"WM");
    assert_eq!(s[3], 2, "record_kind: EffectScheduled");
    assert_eq!(
        u32::from_le_bytes([s[4], s[5], s[6], s[7]]),
        0x0102_0304,
        "effect_seq is little-endian on media, whatever the host is"
    );
    assert_eq!(
        u16::from_le_bytes([s[8], s[9]]),
        8,
        "a schedule body is a fixed eight bytes"
    );
    assert_eq!(u16::from_le_bytes([s[12], s[13]]), 0x1234, "activity kind");
    assert_eq!(u16::from_le_bytes([s[14], s[15]]), 0x40, "input_len");
    assert_eq!(
        u32::from_le_bytes([s[16], s[17], s[18], s[19]]),
        0xDEAD_BEEF,
        "input_crc"
    );

    let e = golden::RUN_COMPLETED_EMPTY;
    assert_eq!(e[3], 7, "record_kind: RunCompleted");
    assert_eq!(u16::from_le_bytes([e[8], e[9]]), 0, "an empty payload");
    assert_eq!(e.len(), FRAME_OVERHEAD_BYTES, "the shortest frame there is");
    // The whole reason the frame checksum covers the header: over an empty payload alone it
    // would be `crc32(&[])`, the same fixed number for every terminal record with no result.
    assert_ne!(
        u32::from_le_bytes([e[12], e[13], e[14], e[15]]),
        crc32(&[]),
        "an empty payload must not have a checksum a zeroed page could hold"
    );
}

#[test]
fn an_input_digest_is_what_a_schedule_record_carries() {
    // `EffectScheduled` records an activity input as a length and a digest rather than as
    // bytes, and §08 compares what replay asks for against what history recorded. That is a
    // check only if both sides compute the digest the same way, so there is one definition
    // of it and this pins its round trip through the frame. Without a public producer the
    // field would be a `u32` the codec faithfully moves across the journal with nothing able
    // to put a right value in it.
    // The algorithm is pinned, not just its behaviour. `input_digest`'s output is written
    // to media in `EffectScheduled.input_crc`, so changing which checksum it is changes the
    // wire format — and without this line the body could be swapped for a different CRC, or
    // for `input.len()`, with every other test in this file still green.
    assert_eq!(
        frame::input_digest(b"123456789"),
        0xCBF4_3926,
        "the digest is CRC-32/ISO-HDLC, and this is the value its specification states"
    );

    let input = b"the activity input the workflow passed";
    let digest = frame::input_digest(input);
    assert_eq!(digest, frame::input_digest(input), "pure");
    assert_ne!(digest, frame::input_digest(b"something else"));
    // The same function the frame is sealed with, which is what makes one implementation
    // enough: a digest computed a second way is a second polynomial to keep in step.
    assert_eq!(frame::input_digest(input), crc32(input));

    let record = RecordRef::EffectScheduled {
        seq: EffectSeq(3),
        kind: ActivityKind(1),
        input_len: u16::try_from(input.len()).expect("a short input"),
        input_crc: digest,
    };
    let mut page = [0_u8; SCRATCH];
    let written = frame::encode(&record, ProgramAlign::BYTE, &mut page).expect("room");

    let Some(RecordRef::EffectScheduled {
        input_crc,
        input_len,
        ..
    }) = decoded_record(&page[..written])
    else {
        panic!("the frame holds a schedule record")
    };
    assert_eq!(input_crc, frame::input_digest(input));
    assert_eq!(usize::from(input_len), input.len());
    // The divergence §08 stops: replay reconstructs a different input for the same effect.
    assert_ne!(input_crc, frame::input_digest(b"a different input"));
}

#[test]
fn no_format_version_permits_skipping_an_unknown_kind_yet() {
    // The rule §09 states, checked over every value a version byte can hold rather than at
    // the one value this firmware writes. `Scan` consults the same function, so a version
    // that quietly granted skipping would be visible here before it was visible as a journal
    // read wrong.
    for version in 0..=u8::MAX {
        assert!(
            !frame::permits_unknown_record_skip(version),
            "version {version} grants skipping, which no version does at rung 0.1"
        );
    }
}

#[test]
fn an_alignment_that_is_not_a_power_of_two_still_round_trips_and_scans() {
    // `ProgramAlign` rejects zero and nothing else, and the type's documentation says a
    // power of two is not required — "a type that refused a device's honest geometry would
    // be a type a driver had to lie to". That claim is only worth making if the arithmetic
    // behind it works, so it is exercised rather than asserted: odd strides, a prime, and
    // the widest value a `u16` program size can hold.
    for granularity in [3_u16, 5, 7, 13, 255, u16::MAX] {
        let align = ProgramAlign::new(granularity).expect("a non-zero alignment");
        let records = [
            RecordRef::RunStarted {
                workflow_kind: 1,
                workflow_version: 1,
                input: b"x",
            },
            RecordRef::EffectCompleted {
                seq: EffectSeq(1),
                result: b"yy",
            },
        ];

        let mut journal = vec![ERASED_BYTE; 4 * usize::from(granularity) + 4_096];
        let mut at = 0;
        for record in &records {
            let written = frame::encode(record, align, &mut journal[at..]).expect("room");
            assert_eq!(
                written % usize::from(granularity),
                0,
                "granularity {granularity} left a frame unpadded"
            );
            at += written;
        }

        let mut scan = Scan::new(&journal, align);
        let walked: Vec<Result<RecordRef<'_>, DecodeError>> = scan.by_ref().collect();
        assert_eq!(
            walked,
            records.map(Ok).to_vec(),
            "granularity {granularity}"
        );
        assert_eq!(scan.offset(), at, "granularity {granularity}");
    }
}

#[test]
fn encode_and_encoded_len_together_tell_a_retryable_failure_from_a_permanent_one() {
    // Both come back as `LengthOutOfBounds`, and a caller that retries needs the difference:
    // a bigger buffer fixes one and nothing fixes the other. Asking `encoded_len` first is
    // what separates them, so the pair is tested rather than left as a doc comment.
    let retryable = RecordRef::RunCompleted { result: b"abc" };
    assert!(frame::encoded_len(&retryable, ProgramAlign::BYTE).is_ok());
    assert_eq!(
        frame::encode(&retryable, ProgramAlign::BYTE, &mut [0_u8; 4]),
        Err(DecodeError::LengthOutOfBounds),
        "a buffer four bytes long cannot hold a nineteen-byte frame"
    );

    let permanent_payload = vec![0_u8; MAX_PAYLOAD_BYTES + 1];
    let permanent = RecordRef::RunCompleted {
        result: &permanent_payload,
    };
    assert_eq!(
        frame::encoded_len(&permanent, ProgramAlign::BYTE),
        Err(DecodeError::LengthOutOfBounds),
        "no buffer makes a payload `payload_len` cannot describe encodable"
    );
    let mut roomy = vec![0_u8; MAX_FRAME_BYTES + 64];
    assert_eq!(
        frame::encode(&permanent, ProgramAlign::BYTE, &mut roomy),
        Err(DecodeError::LengthOutOfBounds)
    );
}

#[test]
fn a_scan_at_the_wrong_alignment_refuses_rather_than_reporting_a_clean_end() {
    // Nothing on media says what program granularity a journal was written at. A reader
    // given a smaller one strides short and lands inside a frame's padding — a run of
    // `ERASED_BYTE` — which, without the erased-to-the-end-of-the-journal rule, would read
    // as the ordinary end of history with committed records still ahead of it. Silently
    // returning a truncated prefix is the worst thing this type can do, because everything
    // downstream believes it.
    let writer = ProgramAlign::new(64).expect("a non-zero alignment");
    let mut journal = [ERASED_BYTE; SCRATCH];
    let mut at = 0;
    for record in [
        RecordRef::RunStarted {
            workflow_kind: 1,
            workflow_version: 1,
            input: b"a",
        },
        RecordRef::EffectCompleted {
            seq: EffectSeq(0),
            result: b"b",
        },
        RecordRef::RunCompleted { result: b"c" },
    ] {
        at += frame::encode(&record, writer, &mut journal[at..]).expect("room");
    }

    // Each frame is seventeen to nineteen bytes padded out to sixty-four, so a reader
    // striding by one lands forty-odd bytes into a pad: far more than a header of
    // `ERASED_BYTE`.
    let mut mismatched = Scan::new(&journal, ProgramAlign::BYTE);
    assert!(matches!(
        mismatched.next(),
        Some(Ok(RecordRef::RunStarted { .. }))
    ));
    assert_eq!(
        mismatched.next(),
        Some(Err(DecodeError::IntegrityFailed)),
        "a short stride must be refused, never read as the end of history"
    );
    assert!(mismatched.next().is_none());

    // The same journal at the granularity it was written with walks all three records.
    let matched: Vec<Result<RecordRef<'_>, DecodeError>> = Scan::new(&journal, writer).collect();
    assert_eq!(matched.len(), 3, "{matched:?}");
    assert!(matched.iter().all(Result::is_ok));
}
